-- synthesized from firmware game metadata
titles_list = {}
titles_list["CLV-P-SAAAE"] = { game_code="CLV-P-SAAAE", name="Super Mario World", raw_title="Super Mario World", title="Super Mario World", thumbnail="games/CLV-P-SAAAE/CLV-P-SAAAE.png", players=2, simultaneous=0, save_count=0, sort_raw_title="super mario world", sort_raw_publisher="NINTENDO", release_date="1991-08-18", copyright="Super Mario World ©1990-1991 Nintendo" }
titles_list["CLV-P-SAABE"] = { game_code="CLV-P-SAABE", name="F-ZERO", raw_title="F-ZERO", title="F-ZERO", thumbnail="games/CLV-P-SAABE/CLV-P-SAABE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="f-zero", sort_raw_publisher="NINTENDO", release_date="1991-08-23", copyright="F-ZERO ©1990-1991 Nintendo" }
titles_list["CLV-P-SAAEE"] = { game_code="CLV-P-SAAEE", name="The Legend of Zelda: A Link to the Past", raw_title="The Legend of Zelda: A Link to the Past", title="The Legend of Zelda: A Link to the Past", thumbnail="games/CLV-P-SAAEE/CLV-P-SAAEE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="the legend of zelda: a link to the past", sort_raw_publisher="NINTENDO", release_date="1992-04-13", copyright="The Legend of Zelda: A Link to the Past ©1991-1992 Nintendo" }
titles_list["CLV-P-SAAFE"] = { game_code="CLV-P-SAAFE", name="Super Mario Kart", raw_title="Super Mario Kart", title="Super Mario Kart", thumbnail="games/CLV-P-SAAFE/CLV-P-SAAFE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="super mario kart", sort_raw_publisher="NINTENDO", release_date="1992-09-01", copyright="Super Mario Kart ©1992 Nintendo" }
titles_list["CLV-P-SAAHE"] = { game_code="CLV-P-SAAHE", name="Super Metroid", raw_title="Super Metroid", title="Super Metroid", thumbnail="games/CLV-P-SAAHE/CLV-P-SAAHE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="super metroid", sort_raw_publisher="NINTENDO", release_date="1994-04-18", copyright="Super Metroid ©1994 Nintendo" }
titles_list["CLV-P-SAAJE"] = { game_code="CLV-P-SAAJE", name="EarthBound", raw_title="EarthBound", title="EarthBound", thumbnail="games/CLV-P-SAAJE/CLV-P-SAAJE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="earthbound", sort_raw_publisher="NINTENDO", release_date="1995-06-05", copyright="EarthBound ©1994 Nintendo/APE inc. Scenario:©1994 SHIGESATO ITOI" }
titles_list["CLV-P-SAAKE"] = { game_code="CLV-P-SAAKE", name="Kirby's Dream Course", raw_title="Kirby's Dream Course", title="Kirby's Dream Course", thumbnail="games/CLV-P-SAAKE/CLV-P-SAAKE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="kirby's dream course", sort_raw_publisher="NINTENDO", release_date="1995-02-01", copyright="Kirby's Dream Course ©1994-1995 HAL Laboratory, Inc. / Nintendo" }
titles_list["CLV-P-SAALE"] = { game_code="CLV-P-SAALE", name="Donkey Kong Country", raw_title="Donkey Kong Country", title="Donkey Kong Country", thumbnail="games/CLV-P-SAALE/CLV-P-SAALE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="donkey kong country", sort_raw_publisher="NINTENDO", release_date="1994-11-24", copyright="Donkey Kong Country ©1994 Nintendo" }
titles_list["CLV-P-SAAQE"] = { game_code="CLV-P-SAAQE", name="Kirby Super Star", raw_title="Kirby Super Star", title="Kirby Super Star", thumbnail="games/CLV-P-SAAQE/CLV-P-SAAQE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="kirby super star", sort_raw_publisher="NINTENDO", release_date="1996-09-20", copyright="Kirby Super Star ©1996 HAL Laboratory, Inc. / Nintendo" }
titles_list["CLV-P-SAAXE"] = { game_code="CLV-P-SAAXE", name="Super Punch-Out!!", raw_title="Super Punch-Out!!", title="Super Punch-Out!!", thumbnail="games/CLV-P-SAAXE/CLV-P-SAAXE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="super punch-out!!", sort_raw_publisher="NINTENDO", release_date="1994-09-14", copyright="Super Punch-Out!! ©1994 Nintendo" }
titles_list["CLV-P-SABCE"] = { game_code="CLV-P-SABCE", name="Mega Man X", raw_title="Mega Man X", title="Mega Man X", thumbnail="games/CLV-P-SABCE/CLV-P-SABCE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="mega man x", sort_raw_publisher="CAPCOM", release_date="1993-12-20", copyright="Mega Man X ©CAPCOM CO., LTD. 1993, 2017 ALL RIGHTS RESERVED." }
titles_list["CLV-P-SABDE"] = { game_code="CLV-P-SABDE", name="Super Ghouls'n Ghosts", raw_title="Super Ghouls'n Ghosts", title="Super Ghouls'n Ghosts", thumbnail="games/CLV-P-SABDE/CLV-P-SABDE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="super ghouls 'n ghosts", sort_raw_publisher="CAPCOM", release_date="1991-11-28", copyright="Super Ghouls'n Ghosts ©CAPCOM CO., LTD. 1991, 2017 ALL RIGHTS RESERVED." }
titles_list["CLV-P-SABHE"] = { game_code="CLV-P-SABHE", name="Street Fighter II Turbo: Hyper Fighting", raw_title="Street Fighter II Turbo: Hyper Fighting", title="Street Fighter II Turbo: Hyper Fighting", thumbnail="games/CLV-P-SABHE/CLV-P-SABHE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="street fighter ii' turbo: hyper fighting", sort_raw_publisher="CAPCOM", release_date="1993-08-01", copyright="Street Fighter II Turbo: Hyper Fighting ©CAPCOM U.S.A., INC. 1993, 2017 ALL RIGHTS RESERVED." }
titles_list["CLV-P-SABQE"] = { game_code="CLV-P-SABQE", name="Super Mario RPG: Legend of the Seven Stars", raw_title="Super Mario RPG: Legend of the Seven Stars", title="Super Mario RPG: Legend of the Seven Stars", thumbnail="games/CLV-P-SABQE/CLV-P-SABQE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="super mario rpg: legend of the seven stars", sort_raw_publisher="NINTENDO", release_date="1996-05-13", copyright="Super Mario RPG: Legend of the Seven Stars ©1996 Nintendo / SQUARE ENIX CO., LTD." }
titles_list["CLV-P-SABRE"] = { game_code="CLV-P-SABRE", name="Secret of Mana", raw_title="Secret of Mana", title="Secret of Mana", thumbnail="games/CLV-P-SABRE/CLV-P-SABRE.png", players=3, simultaneous=1, save_count=0, sort_raw_title="secret of mana", sort_raw_publisher="SQUARE ENIX", release_date="1993-10-03", copyright="Secret of Mana ©1993 SQUARE ENIX CO., LTD." }
titles_list["CLV-P-SABTE"] = { game_code="CLV-P-SABTE", name="Final Fantasy III", raw_title="Final Fantasy III", title="Final Fantasy III", thumbnail="games/CLV-P-SABTE/CLV-P-SABTE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="final fantasy iii", sort_raw_publisher="SQUARE ENIX", release_date="1994-10-11", copyright="Final Fantasy III ©1994 SQUARE ENIX CO., LTD." }
titles_list["CLV-P-SACBE"] = { game_code="CLV-P-SACBE", name="Super Castlevania IV", raw_title="Super Castlevania IV", title="Super Castlevania IV", thumbnail="games/CLV-P-SACBE/CLV-P-SACBE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="super castlevania iv", sort_raw_publisher="KONAMI", release_date="1991-12-01", copyright="Super Castlevania IV ©1991 Konami Digital Entertainment" }
titles_list["CLV-P-SACCE"] = { game_code="CLV-P-SACCE", name="CONTRA III THE ALIEN WARS", raw_title="CONTRA III THE ALIEN WARS", title="CONTRA III THE ALIEN WARS", thumbnail="games/CLV-P-SACCE/CLV-P-SACCE.png", players=2, simultaneous=1, save_count=0, sort_raw_title="contra iii the alien wars", sort_raw_publisher="KONAMI", release_date="1992-04-01", copyright="CONTRA III THE ALIEN WARS ©1992 Konami Digital Entertainment" }
titles_list["CLV-P-SADGE"] = { game_code="CLV-P-SADGE", name="Star Fox", raw_title="Star Fox", title="Star Fox", thumbnail="games/CLV-P-SADGE/CLV-P-SADGE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="star fox", sort_raw_publisher="NINTENDO", release_date="1993-03-01", copyright="Star Fox ©1993 Nintendo" }
titles_list["CLV-P-SADJE"] = { game_code="CLV-P-SADJE", name="Yoshi's Island", raw_title="Yoshi's Island", title="Yoshi's Island", thumbnail="games/CLV-P-SADJE/CLV-P-SADJE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="yoshi's island", sort_raw_publisher="NINTENDO", release_date="1995-10-04", copyright="Yoshi's Island ©1995 Nintendo" }
titles_list["CLV-P-SADKE"] = { game_code="CLV-P-SADKE", name="Star Fox 2", raw_title="Star Fox 2", title="Star Fox 2", thumbnail="games/CLV-P-SADKE/CLV-P-SADKE.png", players=1, simultaneous=0, save_count=0, sort_raw_title="star fox 2", sort_raw_publisher="NINTENDO", release_date="2017-01-01", copyright="Star Fox 2 ©2017 Nintendo" }
