#!/usr/bin/env python3
"""
Generate emu/gba/gba_bios_data.h from a GBA BIOS binary.

The GBA BIOS is copyrighted and is NOT committed to this repo (see .gitignore).
Dump your own 16 KB gba_bios.bin (or use an open-source replacement BIOS) and run:

    ./gen_bios_header.py /path/to/gba_bios.bin

gba_driver.c #includes the generated header and hands the 16 KB to the core via
load_bios_mem(). build_core_gba.sh will remind you if it is missing.
"""
import sys, os

def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    data = open(sys.argv[1], "rb").read()
    if len(data) != 16384:
        raise SystemExit("expected a 16384-byte GBA BIOS, got %d bytes" % len(data))
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gba_bios_data.h")
    with open(out, "w") as f:
        f.write("/* GBA BIOS (16 KB), embedded so LK needs no BIOS file/partition.\n")
        f.write(" * Generated by gen_bios_header.py - do NOT commit (copyrighted). */\n")
        f.write("#ifndef GBA_BIOS_DATA_H\n#define GBA_BIOS_DATA_H\n")
        f.write("static const unsigned char gba_bios_data[16384] = {\n")
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(str(b) for b in data[i:i+16]) + ",\n")
        f.write("};\n#endif\n")
    print("wrote %s (%d bytes)" % (out, len(data)))

if __name__ == "__main__":
    main()
