CloverConst = {
	Demo = {
		MYPLAY_MARIO_SUSPENTION_SHIFT_X = 80,
		MYPLAY_MARIO_SPIN_MOVE_SPEED = 80,
		MARIO_IN_WAIT_SECONDS = 0.5,
		DISPLAY_CHANGE_LUIGI_Y = 183,
		DISPLAY_CURSOR_END_SECONDS = 0.75,
		REPEAT_DELAY = 0.22,
		MYPLAY_MARIO_SHIFT_X = 50,
		REPEAT_RATE = 0.06,
		MYPLAY_MARIO_SPIN_AFTER_SECONDS = 1.25,
		DISPLAY_CHANGE_LUIGI_X = 670,
		MARIO_OUT_WAIT_SECONDS = 0.125,
		DISPLAY_MARIO_LOOKDOWN_SECONDS = 0.5,
		DISPLAY_CURSOR_START_SECONDS = 1,
		START_SECONDS = 60,
		DISPLAY_MARIO_LOOKUP_SECONDS = 0.25,
		SWITCH_DEMO_WAIT_SECONDS = 0.25,
		AUTOPLAY_START_MARIO_Y = -222,
		DISPLAY_OPTION_COUNT = {
			["crt-filter"] = 3,
			["pixel-perfect"] = 1,
			["keep-aspect-ratio"] = 5
		}
	},
	Chr = {
		WALK_SPEED = 350,
		ALPHA_SPEED_RATE = 5,
		SPIN_MOVE_TIME = 1,
		LOWEST_WALK_TIME = 0.25
	},
	BG = {
		SWITCH_BG_WAIT_SECONDS = 0.25,
		MOSAIC_MAX_SCALE = 8,
		RESUME_CHANGE_ALPHA_SECONDS = 0.375,
		DEMO_BG_DARK_RATE = 0.5,
		default = {
			SCROLL_CURSOR_SPEED = 1.75,
			SCROLL_CURSOR_DECEL = 0.2,
			SCROLL_SMOOTH = true,
			SCROLL_CURSOR_ACCEL = 0.2,
			DEFAULT_SCROLL_SPEED = 0.175,
			SCROLL_CURSOR_SECONDS = 0.2,
			SCROLL_CURSOR_DELAY = 0.05,
			SCROLL_CURSOR_SPEED_MAX = 4
		},
		demo = {
			SCROLL_CURSOR_SPEED = 0,
			SCROLL_CURSOR_DECEL = 0,
			SCROLL_SMOOTH = false,
			SCROLL_CURSOR_ACCEL = 0,
			DEFAULT_SCROLL_SPEED = 0.175,
			SCROLL_CURSOR_SECONDS = 0,
			SCROLL_CURSOR_DELAY = 0,
			SCROLL_CURSOR_SPEED_MAX = 0
		}
	},
	TRANSITION = {
		DURATION = 0.4
	},
	Fade = {
		IN_DURATION = 0.3,
		ROLLBACK_FADE_TYPE = "blind",
		NORMAL_FADE_TYPE = "black",
		OUT_DURATION = 0.1
	},
	Suspension = {
		SELECT_TITLE_MOVE_SECONDS = 0.15,
		OVERWRITE_LOCKED_WIDTH_FIRST = 4,
		OVERWRITE_LOCKED_WIDTH_SECOND = 2,
		POPUP_SCALING_SECONDS = 0.125,
		SELECT_TITLE_POSITION_Y = -150,
		POPUP_START_WAIT_SECCONDS = 0.25,
		DUMMY_IN_POS_Y = -270,
		OVERWRITE_COMPLETE_SECONDS = 0.4,
		DUMMY_OUT_POS_Y = -350,
		OVERWRITE_FIRST_DOWN = -80,
		SELECT_TITLE_CORRECT_X = 20,
		DUMMY_DELAY_FIRST = 1,
		OVERWRITE_SECOND_ADD_DOWN = -20,
		DUMMY_DELAY_USUAL = 0.15,
		OVERWRITE_PRESS_MARGIN_SECONDS = 0
	},
	Priority = {
		FOCUS_TITLE_CURSOR_Z = 30
	},
	Anim = {
		POPUP_SCALING_SECONDS = 0.125
	},
	System = {
		AUTOSHUTDOWN_SECONDS = 3600,
		TIMEOUT_SECOND = 10,
		AUTOCANCEL_SECONDS = 180,
		DIMMING_SECONDS = 300
	},
	Cursor = {
		MENUBAR_PRIORITY_Z = 2,
		MENUBAR_CAPTION_DELAY = 0.25
	}
}
